name: task-test2
on:
  schedule:
  - cron: '3/5 14-15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          curl www.baidu.com/$TT
