name: task-test2
on:
  schedule:
  # 0时区
  - cron: '2/5 6-7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          curl www.baidu.com/$TT
