name: glados签到
on:
  schedule:
  # 0时区
  - cron: '35 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 签到
        run: |
          echo "Beijing Time: $(date -d '+8 hours')"
          checkin='https://glados.rocks/api/user/checkin'
          points='https://glados.space/api/user/points'
          # 调用签到接口
          resData=`curl -sS $checkin -b '${{ secrets.GLADOS_COOKIE_36863 }}' -H 'Content-Type: application/json' -A 'Mozilla/5.0' -d '{"token":"glados.one"}'`
          echo $resData
          curl -sS $points -b '${{ secrets.GLADOS_COOKIE_36863 }}' -H 'Content-Type: application/json' -A 'Mozilla/5.0'
          # 间隔1S
          sleep 1
          resData=`curl -sS $checkin -b '${{ secrets.GLADOS_COOKIE_XL7 }}' -H 'Content-Type: application/json' -A 'Mozilla/5.0' -d '{"token":"glados.one"}'`
          echo $resData
          curl -sS $points -b '${{ secrets.GLADOS_COOKIE_XL7 }}' -H 'Content-Type: application/json' -A 'Mozilla/5.0'
          # 间隔1S
          sleep 1
          resData=`curl -sS $checkin -b '${{ secrets.GLADOS_COOKIE_775151 }}' -H 'Content-Type: application/json' -A 'Mozilla/5.0' -d '{"token":"glados.one"}'`
          echo $resData
          curl -sS $points -b '${{ secrets.GLADOS_COOKIE_775151 }}' -H 'Content-Type: application/json' -A 'Mozilla/5.0'
          # 间隔1S
          sleep 1
          resData=`curl -sS $checkin -b '${{ secrets.GLADOS_COOKIE_ZXL7_FOX }}' -H 'Content-Type: application/json' -A 'Mozilla/5.0' -d '{"token":"glados.one"}'`
          echo $resData
          curl -sS $points -b '${{ secrets.GLADOS_COOKIE_ZXL7_FOX }}' -H 'Content-Type: application/json' -A 'Mozilla/5.0'
          
