name: task-test
on:
  schedule:
  - cron: '0/10 13-14 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          curl www.baidu.com/$TT
